# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Sushant Bajracharya
tagline:             'A journey where I travel, code & hustle'
description:         'Sushant Bajracharya is a founder of Grasruts and founder and a sales guy at A Reason 2 Read and Anti Leech Socks'
baseurl:             ''
gems: [jekyll-seo-tag]

plugins_dir:
  - jekyll-seo-tag

# About/contact
author:
  name:              Sushant Bajracharya
  url:               https://twitter.com/sushantbaj
  email:             sussyoung9@gmail.com

# Custom vars
version:             0.0.1

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
