# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Sushant`s Wisdom
tagline:             'A journey where I travel, code & hustle'
description:         'Hi there, thank you for browsing my site.'
baseurl:             ''
gems: [jekyll-paginate, jekyll-seo-tag]
paginate: 10
paginate_path: "page:num"

plugins_dir:
  - jekyll-seo-tag

# About/contact
author:
  name:              Sushant Bajracharya
  url:               https://twitter.com/sushantbaj
  email:             sussyoung9@gmail.com

# Custom vars
version:             0.0.1

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
