# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Sushant`s Expereince
tagline:             'Follow me on my journey where I travel , code and hustle'
description:         'I believe that our life is too short to not take any risks so here I will write about my trips , inspiational blogs, business , philosophy, organic farming, being resourceful'
baseurl:             ''
gems: [jekyll-paginate]
paginate: 1
paginate_path: "page:num"

# About/contact
author:
  name:              Sushant Bajracharya
  url:               https://twitter.com/mdo
  email:             sussyoung9@gmail.com

# Custom vars
version:             0.0.1

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
