# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Sushant`s Wisdom
tagline:             'Follow me on my journey where I travel , code and hustle'
description:         'Hi there, thank you for browsing my site.'
baseurl:             ''
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"

# About/contact
author:
  name:              Sushant Bajracharya
  url:               https://twitter.com/sushantbaj
  email:             sussyoung9@gmail.com

# Custom vars
version:             0.0.1

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
